spring:
  resources:
    add-mappings: true
    cache:
      cachecontrol:
        max-age: 3600
    chain:
      cache: true
      enabled: true
      compressed: true
      html-application-cache: true
    static-locations: classpath:/static/
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.15.8.109:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 
    hikari:
      pool-name: DateHikarCP
      minimum-idle: 5
      idle-timeout: 1800000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  redis:
    host: 106.15.8.109
    password: 
    port: 6379
    database: 0
    connect-timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5
  rabbitmq:
    host: 106.15.8.109
    username: admin
    password: hjh990324863
    virtual-host: /
    port: 5672
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        # 限制消费者每一次只能处理一条消息
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3
        max-interval: 10000ms
        multiplier: 1
mybatis:
  type-aliases-package: com.hjh.pojo
  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.hjh.mapper: debug
